Fixed pom versioning issue as part of #277
kwhat/jnativehook pull request #367
Opened 2021-10-08 07:53 UTC by fabmars

Fixed pom versioning issue as part of #277
Only thing is, I'm not even letting a default in <revision> else it stays on the resulting pom.xml (in <revision/>, not in <version/>, duh), but I don't thing it's a problem.

2021-10-13 01:54 UTC, kwhat reviewed
I just started playing with this and I still have no idea how it works.

2021-10-13 01:54 UTC, kwhat commented on pom.xml
> -    <revision>2.2-SNAPSHOT</revision>
Why are we removing revision here but leaving the ref `<version>` above?

2021-10-13 01:54 UTC, kwhat commented on pom.xml
> +          <plugin>
I have a feeling this should be closer to line 327 instead of in the jdk 8 profile.

2021-10-13 02:07 UTC, kwhat requested changes

2021-10-13 02:07 UTC, kwhat commented on pom.xml
> +              <updatePomFile>true</updatePomFile>
Lets add `<outputDirectory>${project.build.directory}</outputDirectory>` above `updatePomFile>`

2021-10-13 02:07 UTC, kwhat commented on pom.xml
> +            <configuration>
blank line between `<version>` & `<configuration>`

2021-10-13 02:07 UTC, kwhat commented on pom.xml
> +            <executions>
blank line between `</configuration>` & `<executions>`

2021-10-13 02:07 UTC, kwhat commented on pom.xml
> +              <execution>
blank line between `</execution>` & `<execution>`

2021-10-13 02:07 UTC, kwhat commented on pom.xml
> +            <inherited>true</inherited>
blank line between `</executions>` & `<inherited>`

2021-10-13 02:07 UTC, kwhat commented on pom.xml
> +            <inherited>true</inherited>
Is `<inherited>true</inherited>` required?

2021-10-13 02:09 UTC, kwhat commented
I think it is working.  I tested a few things and it appears to be creating the correct pom now.

2021-10-13 02:10 UTC, kwhat commented on pom.xml
> -    <revision>2.2-SNAPSHOT</revision>
I think we can leave this in as the default so you don't have to build with `-Drevision` every time.

2021-10-13 18:56 UTC, kwhat commented
I just pulled it in with a few other maven fixes.

2021-10-13 18:56 UTC, closed without merging

2021-10-15 00:17 UTC, fabmars commented on pom.xml
> -    <revision>2.2-SNAPSHOT</revision>
I agree leaving it lifts the requirement to specify it, but the resulting pom will still contain the <revision> line with the hardcoded snapshot version on top the <version> line with the correct interpolation. Might be misleading (for whoever opens the jar and checks the pom :)).

2021-10-15 01:20 UTC, kwhat commented on pom.xml
> -    <revision>2.2-SNAPSHOT</revision>
I don't think this is the case for the release build.  Ex: `mvn -Drevision="2.2.1" package` produces a jnativehook-2.2.1.jar  file with following in the pom:

```
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.github.kwhat</groupId>
  <artifactId>jnativehook</artifactId>
  <version>2.2.1</version>
  <name>JNativeHook</name>
  <description>Global keyboard and mouse listeners for Java.</description>
  <url>https://github.com/kwhat/jnativehook</url>
```

It still has the following, but I don't think that would be a problem would it?

```
  <properties>
    <maven.compiler.debug>true</maven.compiler.debug>
    <maven.compiler.multi-release>false</maven.compiler.multi-release>
    <maven.compiler.compilerId>javac</maven.compiler.compilerId>
    <maven.compiler.debuglevel>lines,vars,source</maven.compiler.debuglevel>
    <revision>2.2-SNAPSHOT</revision>
```

What was this new plugin suppose to resolve?

2021-10-15 07:55 UTC, fabmars commented on pom.xml
> -    <revision>2.2-SNAPSHOT</revision>
I don't think that would be a problem.
and the plugin is just solving the <version>${revision}</version> interpolation issue.